### PR TITLE
Ensure that an alpha is selected before progressing

### PR DESCRIPTION
**Pull request by Evan-CTL**
In addition to the more critical assertion that an alpha needs to be selected in order to progress properly I've included a minor refactor of the radio buttons. It is now a standardized unordered list to improve accessibility and the mapped format should help to avoid inconsistencies between the radio buttons in future changes.

### CODE REVIEW

**Review by ndittren — COMMENTED** [review]
I like the refactor but I don't like that I can't just click on the number and have that radio button chosen. Might just be a me preference. Let's get Zarina's opinion.

**Review by zmustapha — CHANGES_REQUESTED** [review]
I agree with Natalia, on clicking the number activate the radio button.

**Comment by Evan-CTL** [comment]
Turns out I forgot to generalize the label for each entry. I've resolved it and removed the bullet points from the list items.

**Review by zmustapha — APPROVED** [review]
Thank you!

**Review by ndittren — APPROVED** [review]

**Pull request merged**
